name: Deploy EMS frontend to Firebase Hosting
runs-on: ubuntu-latest

on: [push]
    branches:
        - master

jobs:
    firebase-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Setup NodeJS
              uses: npm install
            - name: Build app
              uses: npm run build
            - name: Deploy to firebase
              uses: w9jds/firebase-action@master
              with:
                args: deploy --only hosting
              env:
                FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                PROJECT_ID: "ems-employee-managment-system"
                PROJECT_PATH: "./"